// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/permission.proto

package permissionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_proto_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePermissionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_proto_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePermissionResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPermissionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_proto_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_proto_rawDescGZIP(), []int{3}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_proto_permission_proto protoreflect.FileDescriptor

const file_proto_permission_proto_rawDesc = "" +
	"\n" +
	"\x16proto/permission.proto\x12\n" +
	"permission\"2\n" +
	"\x17CreatePermissionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"4\n" +
	"\x18CreatePermissionResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"1\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"3\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\xce\x01\n" +
	"\x11PermissionService\x12]\n" +
	"\x10CreatePermission\x12#.permission.CreatePermissionRequest\x1a$.permission.CreatePermissionResponse\x12Z\n" +
	"\x0fCheckPermission\x12\".permission.CheckPermissionRequest\x1a#.permission.CheckPermissionResponseB!Z\x1ftask-service/proto;permissionpbb\x06proto3"

var (
	file_proto_permission_proto_rawDescOnce sync.Once
	file_proto_permission_proto_rawDescData []byte
)

func file_proto_permission_proto_rawDescGZIP() []byte {
	file_proto_permission_proto_rawDescOnce.Do(func() {
		file_proto_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_permission_proto_rawDesc), len(file_proto_permission_proto_rawDesc)))
	})
	return file_proto_permission_proto_rawDescData
}

var file_proto_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_permission_proto_goTypes = []any{
	(*CreatePermissionRequest)(nil),  // 0: permission.CreatePermissionRequest
	(*CreatePermissionResponse)(nil), // 1: permission.CreatePermissionResponse
	(*CheckPermissionRequest)(nil),   // 2: permission.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),  // 3: permission.CheckPermissionResponse
}
var file_proto_permission_proto_depIdxs = []int32{
	0, // 0: permission.PermissionService.CreatePermission:input_type -> permission.CreatePermissionRequest
	2, // 1: permission.PermissionService.CheckPermission:input_type -> permission.CheckPermissionRequest
	1, // 2: permission.PermissionService.CreatePermission:output_type -> permission.CreatePermissionResponse
	3, // 3: permission.PermissionService.CheckPermission:output_type -> permission.CheckPermissionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_permission_proto_init() }
func file_proto_permission_proto_init() {
	if File_proto_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_permission_proto_rawDesc), len(file_proto_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_permission_proto_goTypes,
		DependencyIndexes: file_proto_permission_proto_depIdxs,
		MessageInfos:      file_proto_permission_proto_msgTypes,
	}.Build()
	File_proto_permission_proto = out.File
	file_proto_permission_proto_goTypes = nil
	file_proto_permission_proto_depIdxs = nil
}
