services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: ./services/user-service
    ports:
      - "8081:8080"
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/user_db?sslmode=disable
    depends_on:
      - postgres

  task-service:
    build: ./services/task-service
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/task_db?sslmode=disable
      JWT_SECRET: dev-secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PERMISSION_GRPC_ADDR: permission-service:9090
    depends_on:
      - postgres
      - rabbitmq
      - permission-service

  permission-service:
    build: ./services/permission-service
    ports:
      - "8082:8080"
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/permission_db?sslmode=disable
      REDIS_ADDR: redis:6379
      JWT_SECRET: dev-secret
    depends_on:
      - postgres
      - redis
  auth-service:
    build: ./services/auth-service
    ports:
      - "8083:8080"
    environment:
      JWT_SECRET: dev-secret
  notification-service:
    build: ./services/notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USER_SERVICE_URL: http://user-service:8080
    depends_on:
      - rabbitmq
      - user-service

volumes:
  postgres_data: